name: Example workflow for Codecov
on: [push]
permissions:
  contents: none
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.7'
    steps:
    - name: Checkout
      run: |
        curl -L https://github.com/jsoref/codecov-action-permissions-test/archive/refs/heads/main.zip > /tmp/main.zip
        home=$(pwd)
        cd /tmp
        unzip main.zip
        rsync -a codecov-action-permissions-test-main/ $home/
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        python3 ./setup.py install
        pytest --cov=./ --cov-report=xml
    - name: debug
      run: |
        find .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true

